### ISSUE TITLE
Only Apple kexts may link against com.apple.kpi.private error

### ISSUE THREAD

**Issue by teknologist** [Micky1979/NVMeP#1]
Hi,

First thanks for your effort as well as the authors of the patches (Pike, Mork, etc.).

When loading the Borg generated kext on Sierra DP4 to DP6, I get this error:
Only Apple kexts may link against com.apple.kpi.private error

![screen shot 2016-08-15 at 19 44 43](https://cloud.githubusercontent.com/assets/148448/17773429/b4921422-654e-11e6-958a-409a19d7a48d.png)

I tried loading through Clover/kext as well as /S/L/E and /L/E...

And The SSD shows like this in IOREG:

![screen shot 2016-08-15 at 19 17 38](https://cloud.githubusercontent.com/assets/148448/17773439/c7f4b47a-654e-11e6-9b66-e72528617b13.png)

Using rehabman's patch on DP3 works perfectly:

![screen shot 2016-08-15 at 18 01 42](https://cloud.githubusercontent.com/assets/148448/17773458/da04e66c-654e-11e6-8a81-458f89a06617.jpg)

Any clue ?

**Comment by Micky1979** [comment]
Thanks for the report. Can you try now and report back with last version?

**Comment by teknologist** [comment]
Hi, Thanks for your fast answer..

Unfortunately the problem persists... I still get the Only Apple kexts may link against com.apple.kpi.private error and the kext fails to load...
Maybe it is the way I compile it on Xcode (I compile it on Xcode on EL CAPITAN)...Any pointers ?

![img_20160818_152623](https://cloud.githubusercontent.com/assets/148448/17775438/88171bcc-6558-11e6-9175-97322d3e5939.jpg)

Also if I kextunload the IONVMEFamily.kext , set debug log and kexload it I get this:

```
sentinel:~ eric$ log show --predicate 'process == "kernel"' --last "1m"
Skipping info and debug messages, pass --info and/or --debug to include.
Filtering the log data using "process == "kernel""
Timestamp                       Thread     Type        Activity             PID    
2016-08-18 15:22:47.645899+0200 0x2fb      Default     0x0                  0      kernel: Resetting IOCatalogue.

2016-08-18 15:23:38.976261+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) AppleNVMe Assert failed: ( LBAFormat->LBA_DATA_SIZE == 12 )
2016-08-18 15:23:38.976266+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) CompleteBuffer
2016-08-18 15:23:38.976272+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) file: /BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-234.1.16/IONVMeBlockStorageDevice.cpp
2016-08-18 15:23:38.976288+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) line: 182
2016-08-18 15:23:38.976289+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) 

2016-08-18 15:23:38.977472+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) AppleNVMe Assert failed: 0 == (status)
2016-08-18 15:23:38.977474+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) QueueDelete
2016-08-18 15:23:38.977476+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) file: /BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-234.1.16/IONVMeBlockStorageDevice.cpp
2016-08-18 15:23:38.977477+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) line: 269
2016-08-18 15:23:38.977478+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) 

2016-08-18 15:23:38.978640+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) virtual bool IONVMeBlockStorageDevice::start(IOService *)::324:failed with status = 0xe00002c7
2016-08-18 15:23:38.978646+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) AppleNVMe Assert failed: result
2016-08-18 15:23:38.978649+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) StartFailureExit
2016-08-18 15:23:38.978665+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) file: /BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-234.1.16/IONVMeController.cpp
2016-08-18 15:23:38.978666+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily) line: 3270
2016-08-18 15:23:38.979453+0200 0x2291     Default     0x0                  0      kernel: (IONVMeFamily)

```

Maybe the patches do not work with Intel 750 SSD past DP3...

Also I think, correct me if I am wrong,  pci devices id don't matter on DP3+ as the patch (Info.plis) uses IOClassName match instead...

**Comment by Micky1979** [comment]
ok, I make CFBundleIdentifier "apple-like"  in a new commit. 
Just to be sure, are you patching the kext targeting the one in the Sierra's partition using -k?

**Comment by Micky1979** [comment]
sorry I see only now your edit. IOClassName as far I remembar never exist in those kexts.
The pci device is actually added if the relative array exist (10.11 kexts). What can make the difference is the "IOPCIClassMatch" if did not match:
Try to generate a new kext with last source, if that does not work try to change it from:
IOPCIClassMatch = 0x01800200&0xffffff00
to
IOPCIClassMatch = 0x01080200&0xffffff00 (Rehabman)

**Comment by teknologist** [comment]
My bad I meant IOPCIClassMatch.

Under IOReg I can see the Intel PCI-E SSD does have an IOPCIClassMatch of 0x01080200 so that should not be an issue...

As per your last fix, It did not show the kpi error anymore but it did panic at boot. launching with debug (So I can see the message before it reboots...) I can see this:

"Couldn't alloc class BorgNVMEController"

![img_20160818_155005](https://cloud.githubusercontent.com/assets/148448/17776281/1ab2a6d8-655c-11e6-8a88-c56b96c05f38.jpg)

And yes I did generate kext using -k:

/usr/local/bin/NVMeP -s 0 -k /Volumes/SIERRA1/System/Library/Extensions/IONVMeFamily.kext

from El Capitan.

I am inclined to think the patches are not compatible with Intel PCI-E SSD... Everybody reporting success tends to have a SAMSUNG PCI-E M2 SSD...

What do you think ?

Thanks again for your help ! 

👍

**Comment by Micky1979** [comment]
Not sure, don't own this ssd. BTW "Couldn't alloc class BorgNVMEController" remind me that IOPCIClassMatch is wrong... (maybe, but better to patch the controllet name firstly)
and I'm intrested in a solution.

**Comment by Micky1979** [comment]
Wait, found something intresting..

**Comment by Micky1979** [comment]
If you want try again.. added missing controller patch (that usually not needed in Clover because it patch the original one)

**Comment by teknologist** [comment]
Thanks, tried again...still panic and reboot...
Any idea how can I report the console message ? reboot is too fast and I can't see the error...

only thing is when I get a quick glimpse before restart it says something about IOBlockStorage...

**Comment by Micky1979** [comment]
From another OS I do not know, but you should have a way to avoid panic on reeboot (kBootArgsFlagRebootOnPanic, you can disable that by setting the bitfield in RtVariables -> BooterConfig). Maybe you can see what it does..

from a running OS looks here http://www.insanelymac.com/forum/topic/282794-darwindumper/page-18#entry2255625

**Comment by teknologist** [comment]
Hi have BooterConfig set to 0x28... Wouldn't that be enough ?

Sorry, i am not very familiar with booterconfig and haven't found anything through googling...

**Comment by Micky1979** [comment]
Sorry to have left the conversation, I had to go...
 instead of 0x28 try the higer value 0x7F, more info here:
http://www.insanelymac.com/forum/topic/304530-clover-change-explanations/#entry2156833

**Comment by teknologist** [comment]
Hi @Micky1979 ,

No worries. it's already so cool that you are helping out with this.

0x7F did not avoid auto reboot but I managed to grab a screenshot:

![screen shot 2016-08-19 at 16 06 33](https://cloud.githubusercontent.com/assets/148448/17813565/25be4188-662c-11e6-9910-25bf6dc9a053.PNG)

Don't know if this helps...

Again I am inclined to think the patches are a no go with intel's PCIE SSD on DP4+... What do you think ?

**Comment by Piker-Alpha** [comment]
You said: "_Using rehabman's patch on DP3 works perfectly_" so does Rehabman's script still work with DP4, DP5 and DP6?

I presume that you don't have the DP3 binary anymore. Let me attach it here. I do this so that you can verify that it still works with Rehabman's script and then give Micky1979's app a go.

[IONVMeFamily_DP3_Factory_Vanilla.zip](https://github.com/Micky1979/NVMeP/files/429088/IONVMeFamily_DP3_Factory_Vanilla.zip)

**Comment by teknologist** [comment]
Nope. Rehabman's script generated kext does not work on DP4+.
I still have a DMG of Sierra DP3 and I can confirm your patches work. Then
when I upgrade to anything DP4+ (and I generate new pacthed kext, either with script or app), the patched kext does not work anymore.

They panic kernel on boot.

That's why I am inclined to think the patches work for Intel 750 PCI SSD
until DP3. After that it is a no go.

I even tried using DP3 patched kext with DP3 vanilla kext on DP4+ but it
throws a linking error.

Many thanks for your efforts!

**Comment by teknologist** [comment]
Right now I am using the Intel 750 SSD PCI-E drive under GNU/linux and performance is amazing...

![screenshot from 2016-08-20 23-51-45](https://cloud.githubusercontent.com/assets/148448/17839743/f02e9a50-67f1-11e6-9eb7-d00b9e31eabc.png)

I hope i'll get it wokring on macOS one day!  ;-)

**Comment by teknologist** [comment]
One difference though between DP3 and DP4+ is that under DP3, with no patches, I couldn't see anything under NVMExpress in System report, where as with DP4+ I can see an Apple SSD Controller, again, with no patch whatsoever..

My guess is that changes made by Apple on DP4 broke your patches compatibility with Intel 750 PCI-E SSDs.

Remember I couldn't get the SSD working under El Capitan (as opposed to Samsung M.2 SSDs)...So there is defeinitely something different between samsung's M.2 SSDs and Intel 750.

**Comment by Piker-Alpha** [comment]
I don't think so. Yes something changed, but to make it better. Let's start by looking at this error:

AppleNVMe Assert failed: ( LBAFormat->LBA_DATA_SIZE == 12 )

You only get to see that when the patches are not applied _or_ when the IONVMeFamily.kext loads before the other kext!

About the linkage error; That is irrelevant to the patches. That is a problem with Micky1979's App. Not pointing any fingers, but that is basically it.

Note: Nobody mentioned the linkage error before the App hits the web. Note that the error  itself is not new, but it cannot be resolved by changing the CSR settings.

**Comment by teknologist** [comment]
> About the linkage error; That is irrelevant to the patches. That is a problem with Micky1979's App. Not pointing any fingers, but that basically it.

Nope, I am talking about not being able to use IONVME Family DP3 kext on DP4. I mean replacing DP4 IONVME Family kext by DP3's and applying the patch.

The kpi linking error was fixed right away 3 days ago.

> You only get to see that when the patches are not applied or when the IONVMeFamily.kext loads before the other kext!

Correct. Once I got the patches applied I got KP as show on my last screenshot. 

What do you need me to do to get more infos ? Are the screenshots from IOREG in first post useful ?

Please NOTE I also tested Rehabman's script to create the patched kext...same problem...KP on boot.

**Comment by teknologist** [comment]
For the sake of clarification I updated the issue title... as the kpi dep error was fixed days ago...unfortunately still does not work for Intel 750 PCI-E SSD...

**Comment by Piker-Alpha** [comment]
Your initial problem was the linkage error, and if that is fixed then so is this issue. Open a new one and add a screenshot that people can read. Thanks.

**Comment by teknologist** [comment]
Ok I re changed this issue title to the original and opened a new one and did a copy and paste of the relevant info!

**Comment by Micky1979** [comment]
Thanks Pike to be there, and sorry to not partecipate to this conversation, I was on vacation.

**Comment by venkat1224** [comment]
Hi all,

I'm able to disable the code signing, and load modules, but facing the issue while linking com.apple.kpi.private

 "Apple kexts may link against com.apple.kpi.private error" How did you solve this issue in linking?
