### ISSUE TITLE
Not working for Intel 750 PCI-E SSD on Sierra DP4 and newer

### ISSUE THREAD

**Issue by teknologist** [Micky1979/NVMeP#2]
This App anbd Rehabman's script generated kext does not work on DP4+.
I still have a DMG of Sierra DP3 and I can confirm your patches work. Then
when I upgrade to anything DP4+ (and I generate new pacthed kext, either with script or app), the patched kext does not work anymore.

They panic kernel on boot.

![25be4188-662c-11e6-9910-25bf6dc9a053 1](https://cloud.githubusercontent.com/assets/148448/17851377/f573eb30-6861-11e6-8502-ccfb21d88d2e.PNG)

I am inclined to think the patches work for Intel 750 PCI SSD
until DP3. After that it is a no go.

I even tried using DP3 patched kext with DP3 vanilla kext on DP4+ but it
throws a linking error.

One difference though between DP3 and DP4+ is that under DP3, with no patches, I couldn't see anything under NVMExpress in System report, where as with DP4+ I can see an Apple SSD Controller, again, with no patch whatsoever..

My guess is that changes made by Apple on DP4 broke your patches compatibility with Intel 750 PCI-E SSDs.

Here is an IOREG:

![c7f4b47a-654e-11e6-9b66-e72528617b13](https://cloud.githubusercontent.com/assets/148448/17851413/2da9f062-6862-11e6-8e7c-e55ae13a5b33.png)

Many thanks for your efforts!

**Comment by Piker-Alpha** [comment]
The patched kext must be loaded _before_ IONVMeFamily.kext from Apple so please check that by opening:

Utilities -> System Information

Check: Software -> Extensions -> IONVMeFamily

**Obtained from** should read "Unknown". Not "Apple". The latter means that you have the wrong kext loaded, and since there can only be one kext active...

What you can do is: sudo nano /S_/L_/Extensions/IONVMeFamily.kext/C*/Info.plist and search for this snippet:

```
<key>GenericNVMeSSD</key>
        <dict>
            <key>CFBundleIdentifier</key>
            <string>com.apple.iokit.IONVMeFamily</string>
            <key>Chipset Name</key>
            <string>SSD Controller</string>
            <key>IOClass</key>
            <string>IONVMeController</string>
            <key>IOPCIClassMatch</key>
            <string>0x01080200&amp;0xffffff00</string>
            <key>IOPCIPauseCompatible</key>
            <true/>
            <key>IOPCITunnelCompatible</key>
            <true/>
            <key>IOProviderClass</key>
            <string>IOPCIDevice</string>
            <key>IOUnitName</key>
            <string>disk</string>
            <key>Physical Interconnect</key>
            <string>PCI-Express</string>
            <key>Physical Interconnect Location</key>
            <string>Internal</string>
            <key>Vendor Name</key>
            <string>Apple</string>
        </dict>
```

Change this:

```
0x01080200&amp;0xffffff00
```

Into something that else to stop it from loading.

**Comment by Micky1979** [comment]
Hi Pike, hi teknologist.
To make a quick test, you can also temporarily remove the Apple kext (after a backup) and see if that is the problem. Patched kext in SLE.
Clover usually add injected kexts to the end of the memory-map (not sure if that matter). Some times have solved just naming it differently (follow the alphabetical order).

**Comment by teknologist** [comment]
> Change this:
> 0x01080200&amp;0xffffff00
> Into something that else to stop it from loading.

Did that and also tried Micky's suggestions.

Results yields to no NVMEspress devies detected but no KP.

See:

![screen shot 2016-08-22 at 15 43 48](https://cloud.githubusercontent.com/assets/148448/17857283/671c7bde-6881-11e6-85d3-f6b3f7a4c0f1.png)

And:

![screen shot 2016-08-22 at 15 43 38](https://cloud.githubusercontent.com/assets/148448/17857289/6d71bbe8-6881-11e6-9753-6091756c4496.png)

That is with either patched kext in /S/L/E or even /L/E.  NOTE it says Loadable:No

As soon as I put it in /CLOVER/kext, boot KPs...

As per this suggestion:

> The patched kext must be loaded before IONVMeFamily.kext from Apple so please check that by opening:
> Utilities -> System Information
> Check: Software -> Extensions -> IONVMeFamily

Can't tell because as soon as I have both kext the system KP on boot...

**Comment by Piker-Alpha** [comment]
Ok so now the patched kext is loaded, but no device(s) show up in System Profiler under NVMExpress. This usually means that the patches are not done, or the wrong patches are applied. Time to check the log file ;)

**Comment by teknologist** [comment]
So Booting in debug mode (-v debug=0x12a) without IONVMEFamily.kext vanilla and putting IONVMEFamilyBorg.kext in /S/L/E I don't get much in the logs. I also tried unloading kext and loading it again:

```
sentinel:Extensions eric$ sudo log config --mode "level:debug"
sentinel:Extensions eric$ sudo kextunload IONVMeFamilyBorg.kext
sentinel:Extensions eric$ sudo kextload IONVMeFamilyBorg.kext
sentinel:Extensions eric$ log show --predicate 'process == "kernel"' --last "1m"
2016-08-22 17:53:11.781837+0200 0x1650    Default   0x0     0    kernel: Couldn't alloc class "BorgPNVMeController"
sentinel:Extensions eric$ 
```

Anything else I can do to get you more infos ?

Thanks again,

Cheers

**Comment by teknologist** [comment]
Booting with -v debug=0x12a acpi_layer=0x08 acpi_level=0x02 msgbuf=309212:

```
Last login: Mon Aug 22 18:04:36 on console
sentinel:~ eric$ cd /System/Library/Extensions/
sentinel:Extensions eric$ sudo log config --mode "level:debug"
Password:
sentinel:Extensions eric$ sudo kextunload IONVMeFamilyBorg.kext
sentinel:Extensions eric$ sudo kextload IONVMeFamilyBorg.kext
sentinel:Extensions eric$ log show --predicate 'process == "kernel"' --last "1m"
Skipping info and debug messages, pass --info and/or --debug to include.
Filtering the log data using "process == "kernel""
Timestamp                       Thread     Type        Activity             PID    
2016-08-22 18:04:47.274387+0200 0x10be     Default     0x0                  0      kernel: (Sandbox) SandboxViolation: softwareupdate_n(454) deny(1) file-read-metadata /Users/eric
2016-08-22 18:05:22.689218+0200 0x2a5      Error       0x0                  0      kernel: (IOHIDFamily) loginwindow is not entitled
2016-08-22 18:05:22.689284+0200 0x234      Error       0x0                  0      kernel: (IOHIDFamily) loginwindow is not entitled
2016-08-22 18:05:22.689379+0200 0x2a5      Error       0x0                  0      kernel: (IOHIDFamily) UserEventAgent is not entitled
2016-08-22 18:05:22.689412+0200 0x234      Error       0x0                  0      kernel: (IOHIDFamily) UserEventAgent is not entitled
2016-08-22 18:05:41.131937+0200 0x1507     Default     0x0                  0      kernel: Couldn't alloc class "BorgPNVMeController"
 --------------------------------------------------------------------------------------------------------------------
Log      - Default:          2, Info:                0, Debug:             0, Error:          4, Fault:          0
Activity - Create:           0, Transition:          0, Actions:           0
sentinel:Extensions eric$ 

```

Not much more...  :-(

**Comment by Micky1979** [comment]
New commit, deleted stupid cast  to void*, using bytes. Please retry.

**Comment by teknologist** [comment]
This one fails to patch:
```
Desktop /usr/local/bin/NVMeP -s 0 /Users/eric/Desktop/IONVMeFamily.kext
NVMeP v1.7 by Micky1979,
program to patch IONVMeFamily.kext.
Patches Author: Pike R.Alpha.
Contributors: Mork vom Ork and RehabMan

using optarg -s 0 (Sierra DP4):
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 01 (DP4)"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 02"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 03"
Success applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 04"
Success applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 05"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 06-07"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 08"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 09-10"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 11"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 12"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 13"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 14"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 15"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 16"
**Error applying patch with Comment "IONVMeFamily Pike R. Alpha Patch 17"
Success applying Controller patch (idea of RehabMan)!
Failed applying binary patches, nothing done.
Failed generating a correct kext, nothing done..
```

**Comment by teknologist** [comment]
Definitely some progress!

So basically I did boot and no NVME drive was detected.
Then I started a terminal and tried to unload/load the kext with debug logs and it said kext was not loaded. But it did load and the drive appeared on the desktop:

![screen shot 2016-08-22 at 20 23 16](https://cloud.githubusercontent.com/assets/148448/17866505/0b438e44-68a7-11e6-8447-058961fe62a0.png)

```
Last login: Mon Aug 22 20:21:05 on console
sentinel:~ eric$ cd /System/Library/Extensions/
sentinel:Extensions eric$ sudo log config --mode "level:debug"
Password:
sentinel:Extensions eric$ sudo kextunload IONVMeFamilyBorg.kext
(kernel) Kext com.apple.patchedByNVMeP.IONVMeFamilyBorg not found for unload request.
Failed to unload com.apple.patchedByNVMeP.IONVMeFamilyBorg - (libkern/kext) not found.
sentinel:Extensions eric$ sudo kextload IONVMeFamilyBorg.kext
```

Now the weird thing is that it doesn't show up in SystemReports nor in drives overview. It does show in diskutil list though.:

![screen shot 2016-08-22 at 20 24 04](https://cloud.githubusercontent.com/assets/148448/17866516/1978d4ba-68a7-11e6-8f52-13eb42f945c9.png)

Definitely some progress! We are almost there!  :-)

**Comment by teknologist** [comment]
Well, Gents,

I re organized everything:
1) "reactivated" vanilla kext in /S/L/E
2) Moved Borg kext to CLOVER/kext/Others

And boom! Voilà!

Everything works great!

![screen shot 2016-08-22 at 20 34 19](https://cloud.githubusercontent.com/assets/148448/17866806/456b2f2c-68a8-11e6-8214-abc10e2066ce.png)

Many thanks!

I'll post a benchmark in a minute or so to see how it works and then i'll close the issue!

**Comment by teknologist** [comment]
Now to the bad news...As I suspected from my earlier experiences on DP3... Read performance is not at all on par with what i get on GNU/Linux or Windows...

![screen shot 2016-08-22 at 20 54 11](https://cloud.githubusercontent.com/assets/148448/17867467/e84c7e10-68aa-11e6-8db6-fa00ba1dd3fe.png)

GNU/Linux:
![f02e9a50-67f1-11e6-9eb7-d00b9e31eabc](https://cloud.githubusercontent.com/assets/148448/17867514/16aa40bc-68ab-11e6-928e-a0d9f614e038.png)

Thanks to both of you @Micky1979 and @Piker-Alpha for your great help !

Hoping things will improve as Apple polishes their driver. ;-)

**Comment by Micky1979** [comment]
Thanks Pike for the good patches He provide, and me for a very stupid (never made before) error, but solved! 👍 
I changed the code that was previously made using CoreFoundation, but was requiring a lot of code. Foundation code is a lot smaller.. just avoid errors  :-)
